[package]
name = "gkmake"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
env_logger = "0.11.5"
glob = "0.3.1"
log = "0.4.22"
miette = { version = "7.2", features = ["fancy"] }
temp-dir = "0.1.13"

[dev-dependencies]
indoc = "2.0.5"
test-log = "0.2.16"
